name: Deploy to Play-with-Docker

on:
  push:
    branches:
      - version2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        
      - name: Pull and Run Container on Play-with-Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 192.168.0.28 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          script: |
            docker pull jinsdb7/projet-2:latest
            docker stop projet-2 || true
            docker rm projet-2 || true
            docker run -d -p 80:80 --name projet-2 jinsdb7/projet-2:latest
